//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zero.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collectrequest
    {
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string Food { get; set; }
        public System.DateTime Preserveuntil { get; set; }
        public int StatusId { get; set; }
        public int? EmpId { get; set; }

        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
